# This file was generated by GoReleaser. DO NOT EDIT.
cask "reloop" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0a349f13c6ebbe31466ad796a3251cc415bd4984261fb29d94515b8078c5de70"
      url "https://github.com/mahibulhaque/reloop/releases/download/v#{version}/reloop-v#{version}-darwin-arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f7e6617e3303d7aa088448d0044e108ee1792ed98eddf697e039a0c9e3a30071"
      url "https://github.com/mahibulhaque/reloop/releases/download/v#{version}/reloop-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "56b7dede356ba803039c9e420143dea869e3690faf5e0d54cc6d0a79e9e881c1"
      url "https://github.com/mahibulhaque/reloop/releases/download/v#{version}/reloop-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "reloop"
  desc "Cron and one-shot job scheduler that runs in-process"
  homepage "https://github.com/mahibulhaque/reloop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reloop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reloop"]
    end
  end

  # No zap stanza required
end
